version: '3'
services:
    nginx:
        container_name: prod-nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./docker/nginx/default.prod.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/snippets/fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf
            - /etc/letsencrypt:/etc/letsencrypt

    php:
        container_name: prod-php
        build:
            dockerfile: Dockerfile.prod
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=atte-database.cpoiqs8q0a02.ap-northeast-1.rds.amazonaws.com
            - DB_PORT=3306
            - DB_DATABASE=db-atte
            - DB_USERNAME=atte-database
            - DB_PASSWORD=atte-password0602

    phpmyadmin:
        container_name: prod-phpmyadmin
        environment:
            - PMA_HOST=atte-database.cpoiqs8q0a02.ap-northeast-1.rds.amazonaws.com
            - PMA_USER=atte-database
            - PMA_PASSWORD=atte-password0602
        ports:
            - 8081:80

    mailhog:
        container_name: prod-mailhog

