services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/${NGINX_CONF_FILE}:/etc/nginx/conf.d/default.conf
      - ${SRC_DIR}:/var/www/src/public
      - ${LETS_ENCRYPT_LIVE}:/etc/letsencrypt/live/atte.ddns.net
      - ${LETS_ENCRYPT_ARCHIVE}:/etc/letsencrypt/archive/atte.ddns.net
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: ./docker/php/${DOCKERFILE}
      args:
        NGINX_CONF_FILE: ${NGINX_CONF_FILE}
        APP_ENV: ${APP_ENV}
    container_name: php
    volumes:
      - ${SRC_DIR}:/var/www/src/public
    ports:
      - "9000:9000"
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.26
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      - PMA_HOST=${DB_HOST}
      - PMA_USER=${DB_USERNAME}
      - PMA_PASSWORD=${DB_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - mysql
